name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    name: Install & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: ./

      - name: Run lint (if configured)
        run: |
          if npm run lint --silent; then echo "lint ok"; else echo "no lint or lint failed"; fi
        working-directory: ./

      - name: Run unit tests
        run: npm test --silent
        working-directory: ./

  integration:
    name: Integration tests (optional)
    needs: build
    runs-on: ubuntu-latest
    if: ${{ secrets.SUPABASE_URL && secrets.SUPABASE_SERVICE_KEY && secrets.SESSION_SECRET }}
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
      PRODUCT_IMAGES_BUCKET: ${{ secrets.PRODUCT_IMAGES_BUCKET }}
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      AUTH_U: ${{ secrets.AUTH_U }}
      AUTH_P: ${{ secrets.AUTH_P }}
      ADMIN_ID: ${{ secrets.ADMIN_ID }}
      ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
      PORT: 8080
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: ./

      - name: Start server
        run: |
          nohup npm start &
        working-directory: ./

      - name: Wait for server health
        run: |
          for i in {1..30}; do
            if curl -sSf "http://localhost:8080/health" >/dev/null 2>&1; then
              echo "server up"; exit 0
            fi
            sleep 1
          done
          echo "server did not become healthy"; exit 1

      - name: Run cross-user integration test
        run: API_BASE=http://localhost:8080/api npm run test:cross-user
        working-directory: ./

      - name: Run profile integration test
        run: API_BASE=http://localhost:8080/api ./test/profile_integration.sh
        working-directory: ./
